[package]
name = "seltrans"
version = "0.1.0"
edition = "2024"

[dependencies]
adw = { version = "0.9.2", package = "libadwaita", features = ["v1_5"] }
async-channel = "2.5.0"
futures-util = "0.3.34"
gtk = { version = "0.11.4", package = "gtk4", features = ["v4_18"] }
ksni = "0.3.6"
reqwest = { version = "0.13.4", default-features = false, features = ["rustls", "json", "stream", "http2", "system-proxy"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
tokio = { version = "1.53.1", features = ["rt-multi-thread", "macros"] }

[profile.release]
lto = "thin"
codegen-units = 1
strip = true
